const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const state={profile:localStorage.getItem('dailyBriefProfile')||'pete',data:null,calendarRange:'soon'};
const meta={pete:{name:'Pete',intro:'Your day, filtered down to the things worth knowing.'},sofia:{name:'Sofia',intro:'Your personalised day, without having to hunt for it.'},us:{name:'',intro:'One shared view of the day ahead.'}};
function linkEl(tag,item,cls){const el=document.createElement(item.url?'a':tag);el.className=cls;if(item.url){el.href=item.url;el.target='_blank';el.rel='noopener noreferrer'}return el}
function renderRows(container,items=[],empty='Nothing listed'){container.innerHTML='';if(!items.length){container.innerHTML=`<div class="empty">${empty}</div>`;return}items.forEach(item=>{const el=linkEl('div',item,'list-row');el.innerHTML=`${item.meta?`<div class="meta">${item.meta}${item.source?` · ${item.source}`:''}</div>`:''}<h3>${item.title}</h3>${item.summary?`<p>${item.summary}</p>`:''}`;container.appendChild(el)})}
function renderInterests(items=[]){const box=$('#interestGrid');box.innerHTML='';items.slice(0,3).forEach((item,i)=>{const el=linkEl('div',item,'interest-card'+(i===2?' wide':''));el.innerHTML=`<span>${item.section||'For you'}</span><h3>${item.title}</h3>${item.source?`<small>${item.source}</small>`:''}${item.summary?`<p>${item.summary}</p>`:''}`;box.appendChild(el)});if(!items.length)box.innerHTML='<div class="empty">No personalised items yet.</div>'}
function renderWatch(items=[]){const box=$('#watchStrip');box.innerHTML='';items.slice(0,3).forEach((item,i)=>{const el=linkEl('div',item,'watch-card');el.innerHTML=`<div><small>${item.source||(i===0?'Top pick':'Worth a look')}</small><b>${item.title}</b></div>`;box.appendChild(el)});if(!items.length)box.innerHTML='<div class="empty">No watch recommendations yet.</div>'}
function renderGroups(groups={}){const box=$('#contentGroups');box.innerHTML='';Object.entries(groups).forEach(([name,items])=>{if(!items?.length)return;const g=document.createElement('section');g.className='content-group';g.innerHTML=`<h3>${name}</h3><div class="group-list"></div>`;renderRows($('.group-list',g),items);box.appendChild(g)});if(!box.children.length)box.innerHTML='<div class="empty">No additional sections yet.</div>'}
function startOfDay(d=new Date()){const x=new Date(d);x.setHours(0,0,0,0);return x}
function mondayEnd(){const now=startOfDay(),day=now.getDay()||7,end=new Date(now);end.setDate(now.getDate()+(7-day));end.setHours(23,59,59,999);return end}
function monthEnd(){const now=new Date();return new Date(now.getFullYear(),now.getMonth()+1,0,23,59,59,999)}
function eventStart(e){return new Date(e.start||e.date||Date.now())}function eventEnd(e){return new Date(e.end||e.start||e.date||Date.now())}
function eventAnchor(e){const today=startOfDay(),start=eventStart(e),end=eventEnd(e);return start<today&&end>today?today:start}
function calendarLabel(e){const d=eventStart(e),end=eventEnd(e),today=startOfDay(),tomorrow=new Date(today);tomorrow.setDate(today.getDate()+1);const dayAfter=new Date(tomorrow);dayAfter.setDate(tomorrow.getDate()+1);if(d<today&&end>today)return `Ongoing${e.time&&e.time!=='All day'?` · ${e.time}`:''}`;let dateLabel=d.toLocaleDateString('en-GB',{weekday:'short',day:'numeric',month:'short'});if(d>=today&&d<tomorrow)dateLabel='Today';else if(d>=tomorrow&&d<dayAfter)dateLabel='Tomorrow';return `${dateLabel}${e.time?` · ${e.time}`:''}`}
function filterCalendar(items,range){const now=startOfDay(),tomorrow=new Date(now);tomorrow.setDate(now.getDate()+1);const dayAfter=new Date(tomorrow);dayAfter.setDate(tomorrow.getDate()+1);const weekEnd=mondayEnd(),mEnd=monthEnd();return items.filter(e=>{const s=eventStart(e),end=eventEnd(e),active=end>now&&s<tomorrow;if(range==='today')return active;if(range==='tomorrow')return end>tomorrow&&s<dayAfter;if(range==='week')return end>now&&s<=weekEnd;if(range==='month')return end>now&&s<=mEnd;return end>now}).sort((a,b)=>eventAnchor(a)-eventAnchor(b)).slice(0,range==='soon'?6:40)}
function renderCalendar(items=[]){items=[...items].sort((a,b)=>eventAnchor(a)-eventAnchor(b));const box=$('#calendarList'),filtered=filterCalendar(items,state.calendarRange);box.innerHTML='';if(!filtered.length){box.innerHTML='<div class="empty">Nothing in this view.</div>'}else filtered.forEach(e=>{const row=document.createElement('div');row.className='calendar-row'+(e.color?'':' no-event-colour');if(e.color)row.style.setProperty('--event-color',e.color);row.innerHTML=`<div class="event-rail"></div><div class="event-time">${calendarLabel(e)}</div><div class="event-copy"><h3>${e.title}</h3>${e.summary?`<p>${e.summary}</p>`:''}</div>`;box.appendChild(row)});$$('[data-calendar-range]').forEach(b=>b.classList.toggle('active',b.dataset.calendarRange===state.calendarRange));const todayCount=filterCalendar(items,'today').length,tomorrowCount=filterCalendar(items,'tomorrow').length,weekCount=filterCalendar(items,'week').length,monthCount=filterCalendar(items,'month').length;$('#calendarSummaryCards').innerHTML=`<button data-quick-range="today"><b>${todayCount}</b><span>Today</span></button><button data-quick-range="tomorrow"><b>${tomorrowCount}</b><span>Tomorrow</span></button><button data-quick-range="week"><b>${weekCount}</b><span>This week</span></button><button data-quick-range="month"><b>${monthCount}</b><span>This month</span></button>`;$$('[data-quick-range]').forEach(b=>b.addEventListener('click',()=>{state.calendarRange=b.dataset.quickRange;renderCalendar(items)}));const next=filterCalendar(items,'soon')[0];$('#calendarCount').textContent=next?calendarLabel(next).split(' · ')[0]:'—';$('#calendarSummary').textContent=next?next.title:'nothing soon'}
function render(data){state.data=data;const p=meta[state.profile];$('#greeting').textContent=state.profile==='us'?'Morning.':`Morning, ${p.name}.`;$('#intro').textContent=p.intro;$('#profileAvatar').textContent=state.profile==='us'?'US':p.name[0];$('#briefDate').textContent=data.updatedLabel||'Latest brief';$('#weatherTemp').textContent=data.weather?.temp||'—';$('#weatherSummary').textContent=data.weather?.summary||'Forecast unavailable';const total=Object.values(data.sections||{}).reduce((n,v)=>n+(Array.isArray(v)?v.length:0),0);$('#storyCount').textContent=total;const lead=data.lead||data.interests?.[0]||{};$('#leadCard h3').textContent=lead.title||'Your brief is ready.';$('#leadCard p').textContent=lead.summary||lead.source||'Fresh items will appear here after the morning refresh.';renderCalendar(data.calendar||[]);renderInterests(data.interests);renderWatch(data.watch);renderGroups(data.sections)}
async function loadProfile(profile){state.profile=profile;localStorage.setItem('dailyBriefProfile',profile);$$('[data-profile]').forEach(b=>b.classList.toggle('active',b.dataset.profile===profile));try{const res=await fetch(`data/${profile}.json?cb=${Date.now()}`,{cache:'no-store'});if(!res.ok)throw new Error(`HTTP ${res.status}`);render(await res.json())}catch(err){console.error(err);render({updatedLabel:'Data unavailable',weather:{temp:'—',summary:'Could not load data'},calendar:[],interests:[],watch:[],sections:{}})}}
$$('[data-profile]').forEach(b=>b.addEventListener('click',()=>loadProfile(b.dataset.profile)));$$('[data-scroll]').forEach(b=>b.addEventListener('click',()=>{const id=b.dataset.scroll,target=id==='top'?document.body:document.getElementById(id);target?.scrollIntoView({behavior:'smooth',block:'start'});$$('.bottom-nav button').forEach(x=>x.classList.toggle('active',x===b))}));$$('[data-calendar-range]').forEach(b=>b.addEventListener('click',()=>{state.calendarRange=b.dataset.calendarRange;renderCalendar(state.data?.calendar||[])}));$('#monthToggle')?.addEventListener('click',()=>{state.calendarRange='month';renderCalendar(state.data?.calendar||[]);$('#calendarSection')?.scrollIntoView({behavior:'smooth',block:'start'})});loadProfile(state.profile);