const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const state={profile:localStorage.getItem('dailyBriefProfile')||'pete',data:null};
const meta={pete:{name:'Pete',intro:'Your day, filtered down to the things worth knowing.'},sofia:{name:'Sofia',intro:'Your personalised day, without having to hunt for it.'},us:{name:'',intro:'One shared view of the day ahead.'}};
function linkEl(tag,item,cls){const el=document.createElement(item.url?'a':tag);el.className=cls;if(item.url){el.href=item.url;el.target='_blank';el.rel='noopener noreferrer'}return el}
function renderRows(container,items=[],empty='Nothing listed'){container.innerHTML='';if(!items.length){container.innerHTML=`<div class="empty">${empty}</div>`;return}items.forEach(item=>{const el=linkEl('div',item,'list-row');el.innerHTML=`${item.meta?`<div class="meta">${item.meta}</div>`:''}<h3>${item.title}</h3>${item.summary?`<p>${item.summary}</p>`:''}`;container.appendChild(el)})}
function renderInterests(items=[]){const box=$('#interestGrid');box.innerHTML='';items.slice(0,3).forEach((item,i)=>{const el=linkEl('div',item,'interest-card'+(i===2?' wide':''));el.innerHTML=`<span>${item.section||'For you'}</span><h3>${item.title}</h3>${item.summary?`<p>${item.summary}</p>`:''}`;box.appendChild(el)});if(!items.length)box.innerHTML='<div class="empty">No personalised items yet.</div>'}
function renderWatch(items=[]){const box=$('#watchStrip');box.innerHTML='';items.slice(0,3).forEach((item,i)=>{const el=linkEl('div',item,'watch-card');el.innerHTML=`<div><small>${i===0?'Top pick':'Worth a look'}</small><b>${item.title}</b></div>`;box.appendChild(el)});if(!items.length)box.innerHTML='<div class="empty">No watch recommendations yet.</div>'}
function renderGroups(groups={}){const box=$('#contentGroups');box.innerHTML='';Object.entries(groups).forEach(([name,items])=>{if(!items?.length)return;const g=document.createElement('section');g.className='content-group';g.innerHTML=`<h3>${name}</h3><div class="group-list"></div>`;renderRows($('.group-list',g),items);box.appendChild(g)});if(!box.children.length)box.innerHTML='<div class="empty">No additional sections yet.</div>'}
function render(data){state.data=data;const p=meta[state.profile];$('#greeting').textContent=state.profile==='us'?'Morning.':`Morning, ${p.name}.`;$('#intro').textContent=p.intro;$('#profileAvatar').textContent=state.profile==='us'?'US':p.name[0];$('#briefDate').textContent=data.updatedLabel||'Latest brief';$('#weatherTemp').textContent=data.weather?.temp||'—';$('#weatherSummary').textContent=data.weather?.summary||'Forecast unavailable';$('#calendarCount').textContent=(data.calendar||[]).length;const total=Object.values(data.sections||{}).reduce((n,v)=>n+(Array.isArray(v)?v.length:0),0);$('#storyCount').textContent=total;const lead=data.lead||data.interests?.[0]||{};$('#leadCard h3').textContent=lead.title||'Your brief is ready.';$('#leadCard p').textContent=lead.summary||'Fresh items will appear here after the morning refresh.';renderRows($('#calendarList'),data.calendar,'Nothing coming up');renderInterests(data.interests);renderWatch(data.watch);renderGroups(data.sections)}
async function loadProfile(profile){state.profile=profile;localStorage.setItem('dailyBriefProfile',profile);$$('[data-profile]').forEach(b=>b.classList.toggle('active',b.dataset.profile===profile));try{const res=await fetch(`data/${profile}.json?cb=${Date.now()}`,{cache:'no-store'});if(!res.ok)throw new Error(`HTTP ${res.status}`);render(await res.json())}catch(err){console.error(err);render({updatedLabel:'Data unavailable',weather:{temp:'—',summary:'Could not load data'},calendar:[],interests:[],watch:[],sections:{}})}}
$$('[data-profile]').forEach(b=>b.addEventListener('click',()=>loadProfile(b.dataset.profile)));$$('[data-scroll]').forEach(b=>b.addEventListener('click',()=>{const id=b.dataset.scroll;const target=id==='top'?document.body:document.getElementById(id);target?.scrollIntoView({behavior:'smooth',block:'start'});$$('.bottom-nav button').forEach(x=>x.classList.toggle('active',x===b))}));loadProfile(state.profile);