const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const savedProfile=localStorage.getItem('dailyBriefProfile');
const requestedProfile=new URLSearchParams(location.search).get('profile');
const state={profile:['pete','sofia'].includes(requestedProfile)?requestedProfile:['pete','sofia'].includes(savedProfile)?savedProfile:'pete',data:null,calendarRange:'soon'};
const meta={pete:{name:'Pete',intro:'Your day, filtered down to the things worth knowing.'},sofia:{name:'Sofia',intro:'Your personalised day, without having to hunt for it.'}};
function linkEl(tag,item,cls){const el=document.createElement(item?.url?'a':tag);el.className=cls;if(item?.url){el.href=item.url;el.target='_blank';el.rel='noopener noreferrer'}return el}
function renderRows(container,items=[],empty='Nothing listed'){container.innerHTML='';if(!items.length){container.innerHTML=`<div class="empty">${empty}</div>`;return}items.forEach(item=>{const el=linkEl('div',item,'list-row');el.innerHTML=`${item.meta?`<div class="meta">${item.meta}${item.source?` · ${item.source}`:''}</div>`:''}<h3>${item.title}</h3>${item.summary?`<p>${item.summary}</p>`:''}`;container.appendChild(el)})}
function renderInterests(items=[]){const box=$('#interestGrid');box.innerHTML='';items.slice(0,3).forEach((item,i)=>{const el=linkEl('div',item,'interest-card'+(i===2?' wide':''));el.innerHTML=`<span>${item.section||'For you'}</span><h3>${item.title}</h3>${item.source?`<small>${item.source}</small>`:''}${item.summary?`<p>${item.summary}</p>`:''}`;box.appendChild(el)});if(!items.length)box.innerHTML='<div class="empty">No personalised items yet.</div>'}
function watchBadge(item,i){return item.badge||item.source||(i===0?'Top pick':'Worth a look')}
function watchArtwork(item={}){const src=String(item.artwork||'');return /^https:\/\/static\.tvmaze\.com\/uploads\/images\/original_untouched\//.test(src)&&!/logo|placeholder|favicon|screenshot/i.test(src)?src:''}
function renderWatch(items=[]){const box=$('#watchStrip');box.innerHTML='';items.slice(0,5).forEach((item,i)=>{const artwork=watchArtwork(item),el=linkEl('div',item,'watch-card'+(artwork?' artwork':''));if(artwork){el.dataset.artwork=artwork;el.style.setProperty('--pick-image',`url("${artwork.replace(/"/g,'%22')}")`);el.setAttribute('aria-label',item.artworkAlt||`${item.title} programme artwork`)}el.innerHTML=`<div><small>${watchBadge(item,i)}</small><b>${item.title}</b>${item.meta?`<em>${item.meta}</em>`:''}</div>`;box.appendChild(el)});if(!items.length)box.innerHTML='<div class="empty">No watch recommendations yet.</div>'}
function renderGroups(groups={}){const box=$('#contentGroups');box.innerHTML='';Object.entries(groups).forEach(([name,items])=>{if(!items?.length)return;const g=document.createElement('section');g.className='content-group';g.innerHTML=`<h3>${name}</h3><div class="group-list"></div>`;renderRows($('.group-list',g),items);box.appendChild(g)});if(!box.children.length)box.innerHTML='<div class="empty">No additional sections yet.</div>'}
function startOfDay(d=new Date()){const x=new Date(d);x.setHours(0,0,0,0);return x}
function mondayEnd(){const now=startOfDay(),day=now.getDay()||7,end=new Date(now);end.setDate(now.getDate()+(7-day));end.setHours(23,59,59,999);return end}
function monthEnd(){const now=new Date();return new Date(now.getFullYear(),now.getMonth()+1,0,23,59,59,999)}
function eventStart(e){return new Date(e.start||e.date||Date.now())}function eventEnd(e){return new Date(e.end||e.start||e.date||Date.now())}
function eventAnchor(e){const today=startOfDay(),start=eventStart(e),end=eventEnd(e);return start<today&&end>today?today:start}
function calendarLabel(e){const d=eventStart(e),end=eventEnd(e),today=startOfDay(),tomorrow=new Date(today);tomorrow.setDate(today.getDate()+1);const dayAfter=new Date(tomorrow);dayAfter.setDate(tomorrow.getDate()+1);if(d<today&&end>today)return `Ongoing${e.time&&e.time!=='All day'?` · ${e.time}`:''}`;let dateLabel=d.toLocaleDateString('en-GB',{weekday:'short',day:'numeric',month:'short'});if(d>=today&&d<tomorrow)dateLabel='Today';else if(d>=tomorrow&&d<dayAfter)dateLabel='Tomorrow';return `${dateLabel}${e.time?` · ${e.time}`:''}`}
function filterCalendar(items,range){const now=startOfDay(),tomorrow=new Date(now);tomorrow.setDate(now.getDate()+1);const dayAfter=new Date(tomorrow);dayAfter.setDate(tomorrow.getDate()+1);const weekEnd=mondayEnd(),mEnd=monthEnd();return items.filter(e=>{const s=eventStart(e),end=eventEnd(e),active=end>now&&s<tomorrow;if(range==='today')return active;if(range==='tomorrow')return end>tomorrow&&s<dayAfter;if(range==='week')return end>now&&s<=weekEnd;if(range==='month')return end>now&&s<=mEnd;return end>now}).sort((a,b)=>eventAnchor(a)-eventAnchor(b)).slice(0,range==='soon'?6:40)}
function renderCalendar(items=[]){items=[...items].sort((a,b)=>eventAnchor(a)-eventAnchor(b));const box=$('#calendarList'),filtered=filterCalendar(items,state.calendarRange);box.innerHTML='';if(!filtered.length){box.innerHTML='<div class="empty">Nothing in this view.</div>'}else filtered.forEach(e=>{const row=document.createElement('div');row.className='calendar-row'+(e.color?'':' no-event-colour');if(e.color)row.style.setProperty('--event-color',e.color);row.innerHTML=`<div class="event-rail"></div><div class="event-time">${calendarLabel(e)}</div><div class="event-copy"><h3>${e.title}</h3>${e.summary?`<p>${e.summary}</p>`:''}</div>`;box.appendChild(row)});$$('[data-calendar-range]').forEach(b=>b.classList.toggle('active',b.dataset.calendarRange===state.calendarRange));const todayCount=filterCalendar(items,'today').length,tomorrowCount=filterCalendar(items,'tomorrow').length,weekCount=filterCalendar(items,'week').length,monthCount=filterCalendar(items,'month').length;$('#calendarSummaryCards').innerHTML=`<button data-quick-range="today"><b>${todayCount}</b><span>Today</span></button><button data-quick-range="tomorrow"><b>${tomorrowCount}</b><span>Tomorrow</span></button><button data-quick-range="week"><b>${weekCount}</b><span>This week</span></button><button data-quick-range="month"><b>${monthCount}</b><span>This month</span></button>`;$$('[data-quick-range]').forEach(b=>b.addEventListener('click',()=>{state.calendarRange=b.dataset.quickRange;renderCalendar(items)}));const next=filterCalendar(items,'soon')[0];$('#calendarCount').textContent=next?calendarLabel(next).split(' · ')[0]:'—';$('#calendarSummary').textContent=next?next.title:'nothing soon'}
function weatherIcon(code,size='large'){const sunny=code<=1,partly=code===2,cloudy=code===3||code===45||code===48,rain=code>=51&&code<90,storm=code>=90;const sun=`<circle cx="32" cy="32" r="10"/><path d="M32 8v8M32 48v8M8 32h8M48 32h8M15 15l6 6M43 43l6 6M49 15l-6 6M21 43l-6 6"/>`;const cloud=`<path d="M18 43h29a9 9 0 0 0 1-18 15 15 0 0 0-28-4A11 11 0 0 0 18 43Z"/>`;const drops=`<path d="M24 49l-3 7M36 49l-3 7M48 49l-3 7"/>`;const bolt=`<path d="M34 47l-5 9h7l-3 8 10-12h-7l4-5"/>`;return `<svg class="weather-svg ${size}" viewBox="0 0 64 64" aria-hidden="true">${sunny?sun:''}${partly?sun+cloud:''}${cloudy?cloud:''}${rain?cloud+drops:''}${storm?cloud+bolt:''}</svg>`}
function renderWeather(wx={}){$('#weatherHeroTemp').textContent=wx.temp||'—';$('#weatherHeroSummary').textContent=wx.summary||'Forecast unavailable';$('#weatherNowIcon').innerHTML=weatherIcon(wx.weatherCode??3);const out=wx.bestOutdoor||{};$('#outdoorTime').textContent=out.label||'—';$('#outdoorDetail').textContent=out.detail||'Hourly forecast unavailable';$('#outdoorWindow').textContent=out.label?`Best outdoors ${out.label}`:'';const box=$('#forecastStrip');box.innerHTML='';(wx.daily||[]).slice(0,7).forEach((d,i)=>{const el=document.createElement('article');el.className='forecast-day'+(i===0?' today':'');const date=new Date(`${d.date}T12:00:00`);el.innerHTML=`<span>${i===0?'Today':date.toLocaleDateString('en-GB',{weekday:'short'})}</span>${weatherIcon(d.weatherCode??3,'small')}<strong>${d.high}°</strong><small>${d.low}° · ${d.rainChance??0}% rain</small><em>${d.summary}</em>`;box.appendChild(el)})}
function renderArsenal(a){
  const panel=$('#arsenalPanel');
  if(state.profile!=='pete'||!a){panel.hidden=true;return}
  panel.hidden=false;
  const last=a.lastResult,next=a.nextFixture;
  $('#lastResultCard').innerHTML=last?`<span>Last result · ${last.competition}</span><strong>Arsenal ${last.result} ${last.opponent}</strong><small>${[last.dateLabel,last.kickoff,last.stadium].filter(Boolean).join(' · ')}</small><div class="last-result-details"><p class="match-scorers"><b>Scorers</b><span>${last.scorersLabel||'No scorers listed'}</span></p><p class="match-summary">${last.summary||'Match summary unavailable.'}</p></div>`:'<span>Last result</span><strong>—</strong><small>No result available</small>';
  $('#nextFixtureCard').innerHTML=next?`<span>Next fixture · ${next.competition}</span><strong>${next.opponent}</strong><small>${next.dateLabel} · ${next.kickoff} · ${next.homeAway==='home'?'Home':'Away'}</small>`:'<span>Next fixture</span><strong>—</strong><small>Fixture unavailable</small>';
  $('#leagueCard').innerHTML=a.leaguePosition?`<span>Premier League</span><strong>${a.leaguePosition}${a.leaguePosition===1?'st':a.leaguePosition===2?'nd':a.leaguePosition===3?'rd':'th'}</strong><small>Current position</small>`:'<span>Premier League</span><strong>—</strong><small>Position unavailable</small>';
  const news=$('#arsenalNews');news.innerHTML='';
  (a.news||[]).slice(0,5).forEach((n,index)=>{const hierarchy=index===0?' arsenal-news-lead':index<3?' arsenal-news-support':' arsenal-news-stream',el=linkEl('div',n,`arsenal-news-item${hierarchy}`);el.innerHTML=`<span>${n.source||'Team news'}</span><b>${n.title}</b>`;news.appendChild(el)});
  const newest=items=>[...(items||[])].sort((left,right)=>(Date.parse(right.publishedAt||'')||0)-(Date.parse(left.publishedAt||'')||0));
  const transfers=$('#arsenalTransfers');transfers.innerHTML='';
  newest(a.transfers).slice(0,6).forEach(item=>{
    const el=linkEl('article',item,'arsenal-transfer-item');
    el.innerHTML=`<div><span>${item.trust||'Trusted report'}</span><small>${item.source||'Trusted source'}${item.meta?` · ${item.meta}`:''}</small></div><b>${item.title}</b>`;
    transfers.appendChild(el);
  });
  if(!transfers.children.length)transfers.innerHTML='<div class="arsenal-transfer-empty">No new trusted men’s first-team transfer update today.</div>';
  const rumours=$('#arsenalTransferRumours');rumours.innerHTML='';
  newest(a.transferRumours).slice(0,5).forEach(item=>{
    const el=linkEl('article',item,'arsenal-transfer-item arsenal-rumour-item');
    el.innerHTML=`<div><span>Unconfirmed · X</span><small>${item.source||'Reporter'}${item.confidence?` · ${item.confidence}`:''}${item.meta?` · ${item.meta}`:''}</small></div><b>${item.title}</b>`;
    rumours.appendChild(el);
  });
  if(!rumours.children.length)rumours.innerHTML='<div class="arsenal-transfer-empty arsenal-rumour-empty">No qualifying reporter posts in the last seven days.</div>';
}
function renderScenery(item={}){if(typeof window.renderWorldFact==='function')window.renderWorldFact(item)}
function render(data){state.data=data;const p=meta[state.profile],updated=data.updatedLabel||'Latest brief',weather=`${data.weather?.temp||'—'} · ${data.weather?.summary||'Forecast unavailable'}`;$('#greeting').textContent=`Hey ${p.name}`;$('#intro').textContent=p.intro;$('#profileAvatar').textContent=p.name;$('#topbarDate').textContent=updated;$('#topbarWeather').textContent=weather;$('#briefDate').textContent=updated;$('#weatherTemp').textContent=data.weather?.temp||'—';$('#weatherSummary').textContent=data.weather?.summary||'Forecast unavailable';const total=Object.values(data.sections||{}).reduce((n,v)=>n+(Array.isArray(v)?v.length:0),0);$('#storyCount').textContent=total;const lead=data.lead||data.interests?.[0]||{};$('#leadCard h3').textContent=lead.title||'Your brief is ready.';$('#leadCard p').textContent=lead.summary||lead.source||'Fresh items will appear here after the morning refresh.';renderScenery(data.worldFact||{});renderWeather(data.weather||{});renderArsenal(data.arsenal);renderCalendar(data.calendar||[]);renderInterests(data.interests);renderWatch(data.watch);renderGroups(data.sections)}
async function loadProfile(profile){state.profile=profile;localStorage.setItem('dailyBriefProfile',profile);$$('[data-profile]').forEach(b=>b.classList.toggle('active',b.dataset.profile===profile));try{const res=await fetch(`data/${profile}.json?cb=${Date.now()}`,{cache:'no-store'});if(!res.ok)throw new Error(`HTTP ${res.status}`);render(await res.json())}catch(err){console.error(err);render({updatedLabel:'Data unavailable',weather:{temp:'—',summary:'Could not load data'},calendar:[],interests:[],watch:[],sections:{}})}}
function scrollBehavior(){return matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'}
$$('[data-profile]').forEach(b=>b.addEventListener('click',()=>loadProfile(b.dataset.profile)));$$('[data-scroll]').forEach(b=>b.addEventListener('click',()=>{const id=b.dataset.scroll,target=id==='top'?document.body:document.getElementById(id);target?.scrollIntoView({behavior:scrollBehavior(),block:'start'});$$('.bottom-nav button').forEach(x=>x.classList.toggle('active',x===b))}));$$('[data-calendar-range]').forEach(b=>b.addEventListener('click',()=>{state.calendarRange=b.dataset.calendarRange;renderCalendar(state.data?.calendar||[])}));$('#monthToggle')?.addEventListener('click',()=>{state.calendarRange='month';renderCalendar(state.data?.calendar||[]);$('#calendarSection')?.scrollIntoView({behavior:scrollBehavior(),block:'start'})});loadProfile(state.profile);
